### PR TITLE
Build on m1 macOS 11.3

### LINKED ISSUE #215: Build Failure on Xcode (Clang) 12
I recently tried to upgrade Homebrew's version of mbedtls here: https://github.com/Homebrew/homebrew-core/pull/66819

Homebrew CI runs tests on all packages that depend on mbedtls, and that included neko. This revealed a build failure using the system (macOS) compiler (Clang):
```
FAILED: libs/std/CMakeFiles/std.ndll.dir/process.c.o 
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -D_GNU_SOURCE -Dstd_ndll_EXPORTS -I. -Ivm -Ilibs/common -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -fno-omit-frame-pointer -MD -MT libs/std/CMakeFiles/std.ndll.dir/process.c.o -MF libs/std/CMakeFiles/std.ndll.dir/process.c.o.d -o libs/std/CMakeFiles/std.ndll.dir/process.c.o -c libs/std/process.c
libs/std/process.c:461:2: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        kill(val_process(vp)->pid,9);
        ^
1 error generated.
```
This can, of course, be fixed by passing `-Wno-implicit-function-declaration`. However, I hope this is something you'd want to fix here too.

CI run logs available here: https://github.com/Homebrew/homebrew-core/runs/1544327702

Incidentally, while I'm here, I should mention that we've been unable to build Neko for Big Sur. I think it could be a CMake issue, so I haven't opened a separate issue.

The problem appears to be that `cmake` has trouble finding system `libiconv`, because system libraries no longer exist in the file system on Big Sur. (They can only be found by, say,`dlopen`.) Details available on request, or in the linked CI run above.

### LINKED ISSUE #221: OS/X ARM (M1 cpu) support?
Right near the top of the main `CMakeLists.txt`:
```
set(CMAKE_OSX_ARCHITECTURES x86_64)
```

This causes the build to fail when building against ARM libraries before we even get to the point of having a binary to test.  From https://github.com/Homebrew/homebrew-core/runs/1948673682?check_suite_focus=true :
```
: && /opt/homebrew/Library/Homebrew/shims/mac/super/clang -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 2.0.0 -current_version 2.3.0 -o bin/libneko.2.3.0.dylib -install_name libneko.2.dylib CMakeFiles/libneko.dir/vm/alloc.c.o CMakeFiles/libneko.dir/vm/builtins.c.o CMakeFiles/libneko.dir/vm/callback.c.o CMakeFiles/libneko.dir/vm/elf.c.o CMakeFiles/libneko.dir/vm/interp.c.o CMakeFiles/libneko.dir/vm/load.c.o CMakeFiles/libneko.dir/vm/objtable.c.o CMakeFiles/libneko.dir/vm/others.c.o CMakeFiles/libneko.dir/vm/hash.c.o CMakeFiles/libneko.dir/vm/module.c.o CMakeFiles/libneko.dir/vm/jit_x86.c.o CMakeFiles/libneko.dir/vm/threads.c.o  /opt/homebrew/lib/libgc.dylib  -ldl  -lm && :
ld: warning: ignoring file /opt/homebrew/lib/libgc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_GC_all_interior_pointers", referenced from:
      _neko_gc_init in alloc.c.o
```

I don't have an M1 mac in my possession at the moment so I can't test this directly, but it looks like that hard-coding of x86_64 has been there since @andyli first added the cmake support https://github.com/HaxeFoundation/neko/commit/5334e62a6e8f3eae8af2d50cd456c2bda3c3b739

Does anyone know if other things are likely to break the architecture was *not* hardcoded?  Obviously the JIT would be busted but I think that's disabled on OS/X anyway(?)

### PR DESCRIPTION
**Pull request by lucyllewy**
Lightly tested: I have succeeded in compiling and executing a hello-world on my m1 MacBook Air. Please treat with extreme prejudice and test it hard, and on other systems than m1 Mac, to ensure I haven't broken things :-)

* `CMakeLists.txt`:
    * Remove hard-coded `x86_64` in macOS builds
    * Set CMake Policy `CMP0068` (RPATH on macOS) to `NEW`
    * Ensure that `NekoTargets.cmake` is set to append in
      `export(TARGETS` command for `nekoml` to appease newer CMake
    * Drop duplicate arch64 detection block

Possibly fixes #221 
Fixes #215 

Signed-off-by: Daniel Llewellyn <diddledan@ubuntu.com>

### CODE REVIEW

**Comment by Uzume** [comment]
Maybe I am wrong here but this PR as it sits right now seems to kill 32-bit builds for macOS. Does homebrew stop supporting such as well? I realize Apple might not support such much but I do not see a reason to exclude such from neko builds.

**Comment by tobil4sk** [comment]
@Uzume The fix for `libs/ui/ui.c` was already applied in #218... If what you're suggesting isn't too complicated then you could open a PR to make a better fix, however otherwise neko is now deprecated so large ports are probably not likely to happen.

As a side note, in case this PR is updated in the future, the fixes to `libs/ssl/ssl.c` have also been applied in #239 as they were necessary for mac in general.

**Comment by Uzume** [comment]
@tobil4sk Yes, I noticed some of the changes had already been merged but thanks for calling them out with links to the other PRs. I see @diddledani just rebased the changes here to fix such.

I am not in a position to work on a Carbon to Cocoa port for `libs/ui/ui.c` as I do not have a macOS build environment available to me for development and testing but maybe one day.

**Comment by tobil4sk** [comment]
The `libs/std/process.c` fix had also been done in #219, however not on the same line so git didn't pick it up, now signal.h is included twice in that file.

**Comment by diddledani** [comment]
Thanks for the ping about the changes already included. I've updated the PR with a rebased copy to include the changes from the main branch so that there isn't any duplicated code - I saw that I had to edit the `ui.c` file because my change and the one committed already were conflicting due to being changed on different lines.

**Comment by diddledani** [comment]
> The `libs/std/process.c` fix had also been done in #219, however not on the same line so git didn't pick it up, now signal.h is included twice in that file.

oops, I missed that one. Thanks for pointing it out. I've pushed again with my change there dedpulicated.

**Comment by Uzume** [comment]
@diddledani I think you would be better off not removing the 32-bit Intel macOS build target and instead just adding the 64-bit M1 build target. Neither of those platforms currently is fully supported here by the Azure Pipelines checks (which likely need to be updated).

You probably should not rip out `CMAKE_OSX_ARCHITECTURES`; see:
* https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html
* https://cmake.org/cmake/help/v2.8.12/cmake.html#prop_tgt:OSX_ARCHITECTURES

I included docs link for cmake 2.8.12 since that is the earliest version supported here.

Currently, you will notice this code is failing the MacStatic check:
```
CMake Error at libs/mysql/CMakeLists.txt:7 (if):
   if given arguments:
 
     "STREQUAL" "i386"
 
   Unknown arguments specified
```
You probably should add a line specifying `darwin64-arm64-cc` and not removing `i386` the target.

**Comment by diddledani** [comment]
My change hasn't "disabled i386" builds. They were already disabled by this line which I've actually removed: https://github.com/HaxeFoundation/neko/pull/224/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL9

**Comment by diddledani** [comment]
Let's see if commit 42a9e00 fixes the testsuite. I've readded `CMAKE_OSX_ARCHITECTURES` and set it to `$NATIVE_ARCH_ACTUAL` by default.

**Comment by Uzume** [comment]
That might work but `CMAKE_OSX_ARCHITECTURES` is used mostly for making fat binaries, e.g., we could change the line to:
```
set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64") 
```
Of course the later compares would then always fail. Those should probably be rectified differently (and not use `CMAKE_OSX_ARCHITECTURES` to determine system arch).

**Comment by diddledani** [comment]
yeah, that's made it worse - now the non static build is broken..

**Comment by tobil4sk** [comment]
On this line the `CMAKE_OSX_ARCHITECTURES` string is being evaluated as an empty string...
https://github.com/HaxeFoundation/neko/blob/b8ff4db70aa1376b4133e5936e6bb6ef68c6bd87/CMakeLists.txt#L60

Maybe on this line NATIVE_ARCH_ACTUAL doesn't exist for some reason??
https://github.com/HaxeFoundation/neko/blob/b8ff4db70aa1376b4133e5936e6bb6ef68c6bd87/CMakeLists.txt#L10

**Comment by Uzume** [comment]
You had the right idea: remove `CMAKE_OSX_ARCHITECTURES` all together.

A quick search of the code shows that `arch_64` is only used in one place `libs/mysql/CMakeLists.txt` for the `WIN32` stuff. That should probably be changed to use a `CMAKE_SIZEOF_VOID_P` directly.

As for `libs/mysql/CMakeLists.txt` I am not sure but I do not think it should be trying to parse `CMAKE_OSX_ARCHITECTURES` either. Obviously it needs to have `darwin64-arm64-cc` added but it needs to use something else to determine that. Maybe `CMAKE_SYSTEM_PROCESSOR` is the right thing.

**Comment by diddledani** [comment]
ok, I think this should get the build working for now. I think we should add a followup issue/pr for removing the parsing of `CMAKE_OSX_ARCHITECTURES` with a better mechanism.

**Comment by Uzume** [comment]
@diddledani You probably could have used `CMAKE_SYSTEM_PROCESSOR` but at least that works and seems to have passed all the checks. I agree further cleanup could be useful.

**Comment by danielo515** [comment]
Thanks for making this work on M1
Currently neko works on my M1, but nekotools fails with

```
❯ nekotools
Uncaught exception - load.c(237) : Failed to load library : /usr/local/lib/neko/std.ndll (dlopen(/usr/local/lib/neko/std.ndll, 0x0001): tried: '/usr/local/lib/neko/std.ndll' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/neko/std.ndll' (no such file), '/usr/local/lib/neko/std.ndll' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')))
```

Does this PR fix that?
